[package]
name = "gielo-game"
version.workspace = true 
edition.workspace = true 
authors.workspace = true 
license.workspace = true

[lib]
path = "lib.rs"

[dependencies]
gielo-sheet.workspace = true
gielo-simulation.workspace = true
gielo-unit.workspace = true
gielo-team.workspace = true

anyhow.workspace = true
decorum.workspace = true
derive_more.workspace = true
log.workspace = true
itertools.workspace = true
serde.workspace = true
slint = { workspace = true, optional = true }

[dev-dependencies]
bincode2.workspace = true