[workspace]
members = ["game", "sheet", "simulation", "slint", "unit"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Adam Obuchowicz <farmaazon@gmail.com>"]

[workspace.dependencies]
gielo-game = { path = "game" }
gielo-sheet = { path = "sheet" }
gielo-simulation = { path = "simulation" }
gielo-slint = { path = "slint" }
gielo-unit = { path = "unit" }

anyhow = "1.0"
chrono = "0.4"
decorum = "0.3"
derive_more = "0.99"
directories = "5.0"
float_eq = "1.0"
rand = "0.8"
rand_distr = "0.4"
roots = { git = "https://github.com/farmaazon/roots-rs.git", rev="5e66f152f0c97608142ed02386ba78e0c15973f5" }
simple_logger = "4.0"
itertools = "0.11"
semver = { version = "1.0", features = ["serde"] }
bincode2 = "2.0"
serde_yaml = "0.9"
slint-build = { git = "https://github.com/farmaazon/slint.git" }

[workspace.dependencies.log]
version = "0.4"
features = ["max_level_info", "release_max_level_warn"]

[workspace.dependencies.serde]
version = "1.0"
features = ["derive"]

[workspace.dependencies.slint]
git = "https://github.com/farmaazon/slint.git"
default_features = false
features = ["compat-1-0", "std", "log", "backend-winit", "renderer-winit-skia", "serde"]

[workspace.dependencies.uom]
version = "0.35"
default-features = false
features = ["f64", "si", "std", "use_serde"]

[package]
name = "gielo"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
gielo-game.workspace = true
gielo-slint.workspace = true

anyhow.workspace = true
bincode2.workspace = true
chrono.workspace = true
derive_more.workspace = true
directories.workspace = true
log.workspace = true
itertools.workspace = true
semver.workspace = true
serde.workspace = true
serde_yaml.workspace = true
simple_logger.workspace = true
slint.workspace = true
