[package]
name = "gielo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
decorum = "0.3"
derive_more = "0.99"
directories = "5.0"
float_eq = "1.0"
rand = "0.8"
rand_distr = "0.4"
roots = { git = "https://github.com/farmaazon/roots-rs.git", rev="5e66f152f0c97608142ed02386ba78e0c15973f5" }
simple_logger = "4.0"
itertools = "0.11"
serde_yaml = "0.9"

[dependencies.log]
version = "0.4"
features = ["max_level_info", "release_max_level_warn"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.slint]
version = "1.2"
default_features = false
features = ["compat-1-0", "std", "log", "backend-winit", "renderer-winit-skia"]

[dependencies.uom]
version = "0.35"
default-features = false
features = ["f64", "si", "std", "use_serde"]

[build-dependencies]
slint-build = "1.2"