[package]
name = "gielo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
decorum = "0.3.1"
derive_more = "0.99.17"
float-cmp = "0.9.0"
lazy_static = "1.4.0"
local_vec = "0.5.0"
roots = "0.0.7"
simple_logger = "2.1.0"
itertools = "0.10.3"
log = "0.4.17"

[dependencies.slint]
version = "0.2.1"
default-features = false
features = ["backend-gl-all", "compat-0-2-0", "std"]

[dependencies.uom]
version = "0.32.0"
default-features = false
features = ["f32", "si", "std"]

[build-dependencies]
slint-build = "0.2.1"