import { SheetModel, StoneModel } from "./SheetModel.slint";

export struct PlayerSkills {
    x-std-dev: float,
    y-std-dev: float,
}

export struct Player {
    name: string,
    skills: PlayerSkills,
    left-handed: bool,
}

export struct Team {
    name: string,
    color: color,
    players: [Player],
}

export struct NewGameParameters {
    ends: int,
    teams: [Team],
    ice-profile: int,
    rules-profile: int,
}

export struct PlayingTeam {
    info: Team,
    first-hammer: bool,
    stones-left: int,
    end-score: [int],
    score: int,
}

export global Shot {
    in-out property <float> hog-to-hog-time: 14.5;
    in-out property <bool> automatic-weight: false;
    in-out property <float> mark-x: 0.0;
    in-out property <float> mark-y: SheetModel.geometry.playing-end.tee-y;
    in-out property <bool> clockwise: true;

    in-out property <string> preview-commands;
    in-out property <StoneModel> preview-result;

    callback update();
}

export global GameModel {
    in-out property <[PlayingTeam]> teams;
    in-out property <int> end;
    in-out property <int> ends;
    in-out property <int> current-team;
    in-out property <int> current-player;
    in-out property <bool> game-running;
    in-out property <bool> thinking;
    in-out property <bool> delivering;
    in-out property <bool> fgz-rule-violated;
    in-out property <bool> no-tick-rule-violated;
    in-out property <bool> end-finished;
    in-out property <int> end-score;
    in-out property <bool> game-finished;

    callback start-new-game(NewGameParameters);
    callback finish-game();
    callback deliver();
    callback proceed();
    callback replace-stones();
    callback save();
}
