import { SheetModel } from "./SheetModel.slint";

export struct Team := {
    name: string,
    color: color,
    stones-left: int,
    end-score: [int],
    score: int,
}

export global Shot := {
    property <float> weight-sec: 3.0;
    property <float> mark-x: 0.0;
    property <float> mark-y: SheetModel.geometry.playing-end.tee-y;
    property <bool> clockwise: true;
}

export global GameModel := {
    property <[Team]> teams;
    property <int> end;
    property <int> current-team;
    property <bool> thinking;
    property <bool> delivering;
    property <bool> fgz-rule-violated;
    property <bool> no-tick-rule-violated;
    property <bool> end-finished;
    property <int> end-score;
    property <bool> game-finished;

    callback start-new-game();
    callback deliver();
    callback proceed();
}
