import { Functions } from "./Functions.slint";
import { GameModel, Shot, Team } from "GameModel.slint";
import { Sheet } from "Sheet.slint";
import { Button, Slider } from "std-widgets.slint";

StoneWaiting := Rectangle {
    property <Team> team;

    height: width;
    background: team.color;
    border-width: 2px;
    border-color: black;
    border-radius: width / 2.0;
}

TeamStonesWaiting := Rectangle {
    property <Team> team;
    property <int> stones;

    height: 20px;
    min-width: height * 8;

    HorizontalLayout {
        for i in stones: StoneWaiting {
             team: root.team;
             width: root.height;
        }
    }
}

ScoreCell := Rectangle {
    property <string> text: "";
    property <int> font-weight: 400;

    width: 30px;
    height: 30px;
    border-width: 1px;
    border-color: black;
    background: white;

    Text {
        width: 100%;
        height: 100%;
        text: root.text;
        font-size: 16px;
        font-weight: root.font-weight;
        horizontal-alignment: center;
        vertical-alignment: center;
    }
}

ScoreBoard := VerticalLayout {
    HorizontalLayout {
        alignment: start;

        ScoreCell {}

        ScoreCell {
            text: "H";
        }

        for end in GameModel.ends: ScoreCell {
            text: end + 1;
        }

        ScoreCell {}
    }


    for team[index] in GameModel.teams: HorizontalLayout {

        ScoreCell {
            background: team.color;
        }

        ScoreCell {
            text: team.first_hammer ? "X" : "";
        }

        for end in GameModel.ends: ScoreCell {
            text: team.end-score.length > end ? team.end-score[end] : "";
            font-weight: 600;
        }

        ScoreCell {
            text: team.score;
            font-weight: 600;
        }
    }
}

LeftPane := Rectangle {
    property <bool> blinking-stone-visible;

    background: #519ee8;

    VerticalLayout {
        spacing: 10px;
        alignment: start;

        Text {
            text: "End " + GameModel.end;
            vertical-stretch: 0;
        }

        for team[index] in GameModel.teams: TeamStonesWaiting {

            property <bool> delivering: GameModel.current-team == index && GameModel.delivering;

            team: team;
            stones: team.stones-left - (delivering && !blinking-stone-visible ? 1 : 0);
            vertical-stretch: 0;
        }

        VerticalLayout {
            alignment: center;
            Text {
                text: "Target time tee-hog: " + weight.value;
            }

            weight := Slider {
                minimum: 2.2;
                maximum: 3.6;
                height: 24px;
                vertical-stretch: 0;
                enabled: GameModel.thinking;
                value <=> Shot.weight-sec;

                changed(v) => {
                    value = Functions.round(v, 2);
                    Shot.update-preview();
                }
            }
        }

        rotation := Button {
            width: 160px;
            height: 32px;
            text: Shot.clockwise ? "Clockwise" : "Counter Clockwise";
            enabled: GameModel.thinking;

            clicked => {
                Shot.clockwise = !Shot.clockwise;
                Shot.update-preview();
            }
        }

        Rectangle {
            width: 160px;
            height: 32px;
            if GameModel.thinking: Button {
                text: "Play";

                clicked => { GameModel.deliver() }
            }
        }

        VerticalLayout {
            width: 160px;
            height: 80px;

            if GameModel.fgz-rule-violated: Text {
                text: "Free Guard Zone rule violated.";
                wrap: word-wrap;
            }

            if GameModel.no-tick-rule-violated: Text {
                text: "No Tick rule violated.";
                wrap: word-wrap;
            }

            if GameModel.end-finished: Text {
                text: "End Finished. " + (GameModel.end-score > 0 ?
                    GameModel.teams[0].name + " scored " + GameModel.end-score + " points."
                : GameModel.end-score < 0 ?
                    GameModel.teams[1].name + " scored " + (-GameModel.end-score) + " points."
                : "");
                wrap: word-wrap;
            }

            VerticalLayout {
                height: 32px;

                if GameModel.no-tick-rule-violated: Button {
                    text: "Replace Stones";

                    clicked => { GameModel.replace-stones() }
                }

                if GameModel.end-finished || GameModel.fgz-rule-violated || GameModel.no-tick-rule-violated: Button {
                    text: GameModel.no-tick-rule-violated ? "Leave Stones" : "Proceed";

                    clicked => { GameModel.proceed() }
                }

                if GameModel.game-finished: Button {
                    text: "Finish";

                    clicked => { GameModel.finish-game() }
                }
            }
        }
    }
}

export Game := Rectangle {
    property <bool> blinking-stone-visible;
    background: left-pane.background;

    HorizontalLayout {
        VerticalLayout {
            HorizontalLayout {
                alignment: center;

                left-pane := LeftPane {
                    blinking-stone-visible: root.blinking-stone-visible;
                    horizontal-stretch: 0;
                }
            }

            HorizontalLayout {
                alignment: center;
                ScoreBoard {}
            }
        }

        sheet := Sheet {
            horizontal-stretch: 0;
        }
    }
}