import { SheetModel, SheetEndGeometryPx } from "./SheetModel.slint";

component Circle inherits Rectangle {
    width: self.border-radius * 2.0;
    height: self.border-radius * 2.0;
}

component House inherits Circle {
    border-radius: SheetModel.geometry-px.house-radius;
    background: red;

    eight-foot := Circle {
        x: (root.width - self.width) / 2.0;
        y: (root.height - self.height) / 2.0;
        border-radius: root.border_radius * 2.0 / 3.0;
        background: white;
    }

    four-foot := Circle {
        x: (root.width - self.width) / 2.0;
        y: (root.height - self.height) / 2.0;
        border-radius: root.border_radius / 3.0;
        background: blue;
    }

    button := Circle {
        x: (root.width - self.width) / 2.0;
        y: (root.height - self.height) / 2.0;
        border-radius: root.border_radius / 12.0;
        background: white;
    }
}

component CenterLine inherits Rectangle {
    x: SheetModel.geometry-px.tee-x - self.width / 2.0;
    y: 0px;
    width: 1px;
    height: SheetModel.geometry-px.height;
    background: black;
}

component TransverseLine inherits Rectangle {
    x: 0px;
    width: SheetModel.geometry-px.width;
    height: 1px;
    background: black;
}

component HogLine inherits TransverseLine {
    height: 4px;
    background: red;
}

component SheetEnd inherits Rectangle {
    in property <SheetEndGeometryPx> positions;
    in property <bool> is-playing-end;
    in property <bool> is-delivery-end: !is-playing-end;

    house := House {
        x: SheetModel.geometry-px.tee-x - self.width / 2.0;
        y: positions.tee-y - self.height / 2.0;
    }

    back-line := TransverseLine {
        y: positions.back-y - (is-delivery-end ? self.height : 0.0);
    }

    tee-line := TransverseLine {
        y: positions.tee-y - self.height / 2.0;
    }

    hog-line := HogLine {
        y: positions.hog-y - (is-playing-end ? self.height : 0.0);
    }
}


export component Ice inherits Rectangle {
    background: white;
    width: SheetModel.geometry-px.width;
    height: SheetModel.geometry-px.height;

    delivery-end := SheetEnd {
        positions: SheetModel.geometry-px.delivery-end;
        is-playing-end: false;
    }

    playing-end := SheetEnd {
        positions: SheetModel.geometry-px.playing-end;
        is-playing-end: true;
    }

    center-line := CenterLine {}


}