import { Functions } from "./Functions.slint";
import { Game } from "./Game.slint";
import { Team, Shot, NewGameTeam, NewGameParameters, GameModel, Player, PlayerSkills } from "./GameModel.slint";
import { Ice } from "./Ice.slint";
import { Profiles } from "./Profiles.slint";
import { StoneModel, SheetEndGeometry, SheetGeometry, SheetModel } from "./SheetModel.slint";
import { NewGame } from "./NewGame.slint";

export {
    Functions,
    GameModel,
    NewGameParameters,
    NewGameTeam,
    Player,
    PlayerSkills,
    Profiles,
    SheetModel,
    SheetEndGeometry,
    SheetGeometry,
    Shot,
    StoneModel
}

export component Main inherits Window {
    in property <bool> blinking-stone-visible;
    in property <NewGameParameters> default-game-parameters;

    preferred-width: 800px;
    preferred-height: 600px;

    if GameModel.game-running: Game {
        blinking-stone-visible: root.blinking-stone-visible;
    }

    if !GameModel.game-running: NewGame {
        parameters: default-game-parameters;
    }
}