import { Functions } from "./Functions.slint";
import { Game } from "./Game.slint";
import { Team, Shot, GameModel } from "./GameModel.slint";
import { Ice } from "./Ice.slint";
import { StoneModel, SheetEndGeometry, SheetGeometry, SheetModel } from "./SheetModel.slint";

export { Functions, GameModel, SheetModel, SheetEndGeometry, SheetGeometry, Shot, StoneModel }

export Main := Window {
    property <bool> blinking-stone-visible;

    preferred-width: 800px;
    preferred-height: 600px;

    Game {
        blinking-stone-visible: root.blinking-stone-visible;
    }
}