import { Button, CheckBox, ComboBox, LineEdit, SpinBox, Slider } from "std-widgets.slint";
import { Functions } from "./Functions.slint";
import { GameModel, NewGameParameters, NewGameTeam, Player, PlayerSkills } from "./GameModel.slint";
import { Profiles } from "./Profiles.slint";

TeamLineOut := Rectangle {
    property <NewGameTeam> team;
    property <[string]> player-titles: ["Lead", "Second", "Third", "Fourth"];

    callback changed(NewGameTeam);

    VerticalLayout {
        spacing: 5px;

        HorizontalLayout {
            spacing: 5px;
            Rectangle {
                width: height;
                horizontal-stretch: 0;
                background: team.color;
                border-width: 2px;
                border-color: black;
            }

            Text {
                vertical-alignment: center;
                text: "Team";
            }

            LineEdit {
                text: team.name;
                edited => {
                    team.name = text;
                    changed(team);
                }
            }
        }

        for player[player-index] in team.players: HorizontalLayout {
            property <PlayerSkills> skills: player.skills;

            spacing: 5px;

            Text {
                width: 50px;
                vertical-alignment: center;
                text: player-titles[player-index] + ":";
            }

            VerticalLayout {
                player-profile := ComboBox {
                    model: Profiles.player-skills;
                    current-value: Profiles.custom-player-skills-label(skills);

                    selected(profile) => {
                        if (current-index != 0) {
                            skills = Profiles.load-player-skills(current-index);
                            team.players[player-index].skills = skills;
                            x-std-dev-slider.value = skills.x-std-dev;
                            y-std-dev-slider.value = skills.y-std-dev;
                            changed(team)
                        }
                    }
                }

                HorizontalLayout {
                    y-std-dev-slider := Slider {
                        value: skills.y-std-dev;
                        minimum: 0.0;
                        maximum: 12.0;

                        changed(value) => {
                            self.value = Functions.round(value, 1);
                            skills.y-std-dev = self.value;
                            team.players[player-index].skills.y-std-dev = self.value;
                            player-profile.current-index = 0;
                            player-profile.current-value = Profiles.custom-player-skills-label(skills);
                            root.changed(team)
                        }
                    }

                    x-std-dev-slider := Slider {
                        value: skills.x-std-dev;
                        minimum: 0.0;
                        maximum: 6.0;

                        changed(value) => {
                            self.value = Functions.round(value, 1);
                            skills.x-std-dev = self.value;
                            team.players[player-index].skills.x-std-dev = self.value;
                            player-profile.current-index = 0;
                            player-profile.current-value = Profiles.custom-player-skills-label(skills);
                            root.changed(team)
                        }
                    }
                }
            }

            CheckBox {
                text: "left-handed";
                checked: player.left-handed;

                toggled => {
                    team.players[player-index].left-handed = checked;
                    changed(team)
                }
            }
        }
    }
}

export NewGame := Rectangle {
    property <NewGameParameters> parameters: {
        ends: 8,
        teams: [],
        ice-profile: 0,
        rules-profile: 0,
    };
    background: #519ee8;

    HorizontalLayout {
        alignment: center;

        VerticalLayout {
            padding: 10px;
            spacing: 10px;
            horizontal-stretch: 0;
            width: 400px;

            TeamLineOut {
                team: parameters.teams[0];

                changed(team) => {
                    parameters.teams[0] = team;
                }
            }

            Text {
                text: "Ice profile:";
            }

            ComboBox {
                model: Profiles.ice;
                current-index: parameters.ice-profile;

                selected(profile) => {
                    parameters.ice-profile = current-index;
                }
            }

            Rectangle {}
        }

        VerticalLayout {
            padding: 10px;
            spacing: 10px;
            horizontal-stretch: 0;
            width: 400px;

            TeamLineOut {
                team: parameters.teams[1];

                changed(team) => {
                    parameters.teams[1] = team;
                }
            }

            Text {
                text: "Rule set:";
            }

            ComboBox {
                model: Profiles.rules;
                current-index: parameters.rules-profile;

                selected(profile) => {
                    parameters.rules-profile = current-index;
                }
            }

            Text {
                text: "Ends:";
            }

            ends := SpinBox {
                minimum: 1;
                maximum: 20;
                value: parameters.ends;
            }

            Rectangle {}

            Button {
                text: "Start!";

                clicked => {
                    // SpinBox, for some reason, does not have "changed" callback;
                    parameters.ends = ends.value;
                    GameModel.start-new-game(parameters);
                }
            }
        }
    }
}