import { Functions } from "./Functions.slint";
import { GameModel, Shot } from "./GameModel.slint";
import { StoneModel, SheetModel } from "./SheetModel.slint";
import { Ice } from "./Ice.slint";
import { ScrollView, Slider } from "std-widgets.slint";

component Mark inherits Rectangle {
    x: Shot.mark-x * SheetModel.pixels-per-foot + SheetModel.geometry-px.tee-x - self.width / 2.0;
    y: Shot.mark-y * SheetModel.pixels-per-foot;
    width: 18px;
    height: 1.8 * self.width;
    background: orange;
    border-radius: self.width / 2.0;
    border-color: black;
    border-width: 2px;

    Rectangle {
        x: (parent.width - self.width) / 2.0;
        y: parent.height;
        width: 8px;
        height: 80px;
        background: black;

        Rectangle {
            x: (Shot.clockwise ? 10px : -self.width - 10px) + parent.width / 2.0;
            y: parent.height - self.height;
            width: 40px;
            height: 8px;
            border-radius: self.height / 2.0;
            background: gray;

            Rectangle {
                x: (Shot.clockwise ? parent.width : 0.0) - self.width / 2.0;
                y: (parent.height - self.height) / 2.0;
                width: 18px;
                height: self.width;
                background: white;
                border-radius: self.width / 2.0;
                border-color: gray;
                border-width: 2px;
            }
        }
    }
}

component Stone inherits Rectangle {
    in property <StoneModel> model;
    in property <bool> preview: false;

    x: model.x * SheetModel.pixels-per-foot + SheetModel.geometry-px.tee-x - self.border-radius;
    y: model.y * SheetModel.pixels-per-foot - self.border-radius;
    border-radius: SheetModel.stone-radius * SheetModel.pixels-per-foot;
    width: self.border-radius * 2.0;
    height: self.border-radius * 2.0;
    background: preview ? transparent : model.color;
    border-width: 2px;
    border-color: preview ? model.color.darker(0.3) : black;
}

component Preview inherits Rectangle {
    width: 100%;
    height: 100%;

    Path {

        x: -1px;
        y: -1px;
        stroke: Shot.preview-result.color.darker(0.5);
        stroke-width: 2px;
        viewbox-x: -SheetModel.geometry.tee-x;
        viewbox-y: 0.0;
        viewbox-width: SheetModel.geometry.width;
        viewbox-height: SheetModel.geometry.height;
        width: SheetModel.geometry-px.width + 2px;
        height: SheetModel.geometry-px.height + 2px;

        commands: Shot.preview-commands;
    }

    Stone {
        model: Shot.preview-result;
        preview: true;
    }
}

export component Sheet inherits ScrollView {
    width: ice.width + 20px;
    viewport-width: ice.width;
    viewport-height: ice.height;
    viewport-y: self.height - SheetModel.geometry-px.playing-end.back-y - 60.px;

    ice := Ice {
        Preview {}
    }

    for stone in SheetModel.stones: Stone {
        model: stone;
    }

    Mark {}

    if GameModel.thinking: TouchArea {
        pointer-event(event) => {
            if (event.kind == PointerEventKind.down && event.button == PointerEventButton.left) {
                Shot.mark-x = (self.pressed-x - SheetModel.geometry-px.tee-x) / SheetModel.pixels-per-foot;
                Shot.mark-y = self.pressed-y / SheetModel.pixels-per-foot;
            } else if (event.kind == PointerEventKind.down && event.button == PointerEventButton.right) {
                Shot.clockwise = !Shot.clockwise;
            }
            Shot.update-preview();
        }
    }
}