[package]
name = "gielo-team"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
gielo-sheet.workspace = true
gielo-unit.workspace = true

derive_more.workspace = true
rand.workspace = true
rand_distr.workspace = true
serde.workspace = true
